### ISSUE TITLE
Typo in the paper of Anatomy of the SIFT Method?

### ISSUE THREAD

**Issue by lionlai1989** [ivreo/sift_anatomy#1]
Hi:
I've been reading the paper of [Anatomy of the SIFT Method](https://www.ipol.im/pub/art/2014/82/?utm_source=doi) and wondering if there is few typos in the figures and equations. It would be great if you could clarify.  
1. In figure 1, should $\sigma^2_1$ and $\sigma^1_2$  be switching places?
![Screenshot from 2022-10-13 09-01-43](https://user-images.githubusercontent.com/5163329/195525057-f3e48600-b5fa-4898-8056-1e0c4e43969f.png)

2. In figure 2, the upsampling scale space starts from $v^0_0$ , but the paper says that
> The construction of the digital scale-space begins with the computation of a seed image denoted by $v^1_0$.
> The entire digital scale-space is derived from this seed image.

So, I am wondering if this is a typo. Should $v^0_0$ be $v^1_0$?
![Screenshot from 2022-10-13 09-04-32](https://user-images.githubusercontent.com/5163329/195525651-724a9b1f-e906-4f16-ae01-6b8999e5029a.png)

3. In your [implementation](https://github.com/ivreo/sift_anatomy/blob/master/src/sift_cli.c#L284), the input images are normalized. But I am wondering if the normalization of the input images is necessary. In the paper, it says that
> The SIFT descriptor is built from the normalized image gradient orientation in the form of quantized histograms.

In your implementation, the pixels are divided by 256 and the input images are png files. I am guessing here the purpose of it is to normalize the pixel to 0-1.

But is it necessary? Shouldn't the process of SIFT algorithm normalize pixels when calculating gradient matrix?

4. In the description of Algorithm 2, should the symbol ${s_N}(k)$ in the following equation be ${s_M}(k)$, no?
![Screenshot from 2022-10-13 09-25-16](https://user-images.githubusercontent.com/5163329/195529944-1a92f41b-3b33-4727-b63e-51feb22c834e.png)

I would be appreciated if you can clarify the above points. Thank you.

**Comment by ivreo** [comment]
Hi,

- In figure 1, You are right, \sigma_s^o should correspond to the s-th scale in the o-th octave. The indices are mixed up. Thank you for pointing that out.

- In the text, "seed image" refers to an image that has been up-sampled and has a relative blur level of \sigma_{min} = 0.8. Notations in the text and the figure are inconsistent. Thanks for pointing it out. 

- You could skip pixel normalization, but then thresholds should be changed accordingly  (in particular for the DoG 3d extrema).

- You're right again. It should read s_M(k).

Thank you.

**Comment by lionlai1989** [comment]
Thank you for your clarifications. :heart_decoration:
